const CONFIG = {
    introTitle: 'Xin chào Trần Linh !',
    introDesc: `Tao là Cường dz `,
    btnIntro: 'hihi',
    title: 'Nếu m đọc được những dòng này 😙',
    desc: 'Thì m phải lựa chọn ',
    btnYes: 'Cho anh 100tr',
    btnNo: ' Ăn đầu buồi ăn cứt ',
    question:'Ăn đấm không',
    btnReply: 'Oke',
    reply: 'Chúc mừng m đã nhận dc quyền cho anh 100tr',
    mess: ' Muahahaha',
    messDesc: 'Thế nhé.',
    btnAccept: 'Okiiiii ',
}
